# Render.com deployment configuration for MediFlow Hospital Management System
services:
  # Monolithic Backend Service
  - type: web
    name: hospital-management-system
    env: java
    plan: free
    buildCommand: cd monolithic-app && mvn clean package -DskipTests
    startCommand: cd monolithic-app && java -Xmx400m -XX:MaxRAMPercentage=75 -Dserver.port=$PORT -jar target/hospital-management-system-2.0.0.jar
    healthCheckPath: /actuator/health
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx400m -XX:MaxRAMPercentage=75
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 86400000
      - key: SPRING_JPA_SHOW_SQL
        value: false
      - key: LOGGING_LEVEL_ROOT
        value: INFO
        
  # React Frontend Service  
  - type: web
    name: mediflow-portal
    env: node
    plan: free
    buildCommand: cd member-portal && npm ci && npm run build
    startCommand: cd member-portal && npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_BASE_URL
        value: https://hospital-management-system.onrender.com
      - key: GENERATE_SOURCEMAP
        value: false

# Database (using H2 in-memory for simplicity on free tier)
# No external database needed - H2 is embedded

# Build settings optimized for Render free tier
# - Build timeout: Under 15 minutes
# - Memory usage: Under 512MB
# - No persistent storage required (H2 in-memory)
# - Automatic deployment on git push