# Production Configuration
spring:
  config:
    activate:
      on-profile: prod
  
  # Database Configuration - H2 in-memory for lightweight deployment
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:hospital_db}
    driver-class-name: ${DATABASE_DRIVER:org.h2.Driver}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:password}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 600000
  
  # H2 Console Configuration - disabled in production
  h2:
    console:
      enabled: false
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:create-drop}
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
    open-in-view: false

# Server Configuration - optimized for Render.com
server:
  port: ${PORT:8080}
  tomcat:
    threads:
      max: 50
      min-spare: 5
    connection-timeout: 30000
    keep-alive-timeout: 30000
    max-connections: 200
  error:
    include-stacktrace: never
    include-message: always

# Logging Configuration - production optimized
logging:
  level:
    root: INFO
    com.hospital: INFO
    org.springframework.security: WARN
    org.springframework.web: WARN
    sql: ERROR

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:MediFlowHospitalManagementSystemSecureJWTSigningKey2024ForHS512Algorithm}
  expiration: ${JWT_EXPIRATION:86400000}

# CORS Configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://mediflow-portal.onrender.com}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# API Documentation Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

# Management Endpoints - limited in production
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Security optimizations
spring.security.user.password: disabled