# Production Configuration
spring:
  config:
    activate:
      on-profile: prod
  
  # Database Configuration - PostgreSQL for production (shared mediflow database)
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
  sql:
    init:
      mode: always

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

# Server Configuration - optimized for Render.com
server:
  port: ${PORT:8080}
  tomcat:
    threads:
      max: 50
      min-spare: 5
    connection-timeout: 30000
    keep-alive-timeout: 30000
    max-connections: 200
  error:
    include-stacktrace: never
    include-message: always

# Logging Configuration - production optimized
logging:
  level:
    root: INFO
    com.hospital: INFO
    org.springframework.security: WARN
    org.springframework.web: WARN
    sql: ERROR

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

# CORS Configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# API Documentation Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

# Management Endpoints - limited in production
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Security optimizations
spring.security.user.password: disabled